TER-103 revoke bucket read only role
keboola/php-storage-driver-common pull request #34
Opened 2023-02-08 15:55 UTC by martinjunger

2023-02-13 12:40 UTC, jirkasemmler requested changes
jsi evidentne zmenil vsude chmod, prosim fixni to

2023-02-13 12:40 UTC, jirkasemmler commented on proto/bucket.proto
> +  bool ignoreErrors = 3; // if true all backend errors should be ignored and command will always pass
proc to potrebujeme? nemel by ten ignore byt v connection?

2023-02-14 14:38 UTC, martinjunger commented
> jsi evidentne zmenil vsude chmod, prosim fixni to

znovu jsem zbuildil `dev` container a pustil `composer protobuf` a pomohlo to - stejne jako predtim 🤷

2023-02-14 15:06 UTC, jirkasemmler commented on proto/bucket.proto
> +  bool ignoreErrors = 3; // if true all backend errors should be ignored and command will always pass
dava to smysl na vicekrokovych operacich -> ergo by to melo byt i tady

2023-02-14 15:06 UTC, jirkasemmler approved these changes

2023-02-15 08:54 UTC, merged